<?php
/**
 * @author:  MonishTrivedi
 * @package: TrainingMonish_LoginIP
 */

?>

<h1>
    <?= $this->errorCode ? $block->escapeHtml($this->errorCode . ' - ') : '' ?>
    <?= $block->escapeHtml($this->pageTitle) ?>
</h1>
<?php if ($this->_config->action == '') : ?>
    <p><em><?= $block->escapeHtml(__('Exception printing is disabled by default for security reasons.')) ?></em></p>
<?php elseif ($this->reportData) : ?>
    <div class="trace-container">
        <div class="trace">
            <pre><?= $block->escapeHtml($this->reportData) ?><br/>
Please read the following materials to resolve the problem:
 - User Guide http://docs.mageplaza.com/security/
 - FAQs https://www.mageplaza.com/faqs/
 - Issues https://github.com/mageplaza/magento-2-security/issues'
            </pre>
        </div>
    </div>
<?php endif; ?>
