<div class="field father-name required">
    <label class="label" for="father-name">
      <span><?= $block->escapeHtml(__('Fathers Name')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="father-name" id="ather-name" value="" title="<?= $block->escapeHtmlAttr(__('Fathers Name')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
<div class="field mother-name required">
    <label class="label" for="mother-name">
      <span><?= $block->escapeHtml(__('Mothers Name')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="mother-name" id="ather-name" value="" title="<?= $block->escapeHtmlAttr(__('Mothers Name')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
