<?php
/**
 * @package    TrainingMonish_GridForm
 * @author     monish.trivedi@krishtechnolabs.com
 */
?>
<?php
    $singleData = $block->getSingleData();      
?>
<div>
    <h3>Title</h3>
    <p><?php echo $singleData->getTitle(); ?></p>   
</div>
<div>
    <h3>Author</h3>
    <p><?php echo $singleData->getAuthor(); ?></p>
</div>
<div>
    <h3>Content</h3>
    <p><?php echo $this->_filterProvider->getPageFilter()->filter($singleData->getContent()); ?></p>
</div>
<div>
    <h3>Preferred Language</h3>
    <p><?php echo $singleData->getPreferredLanguage(); ?></p>
</div>
<div>
    <h3>Country</h3>
    <p><?php echo $singleData->getCountry(); ?></p>
</div>
<div>
    <h3>Newsletter</h3>
    <p><?php echo $singleData->getNewsletter(); ?></p>
</div>
<div>
    <h3>Location</h3>
    <p><?php echo $singleData->getLocation(); ?></p>
</div>
<div>
    <h3>Date</h3>
    <p><?php echo $singleData->getCreatedAt(); ?></p>
</div>